#ifndef VALUE_HXX
#define VALUE_HXX

const int DEFAULT_WINDOW_WIDTH = 500;
const int DEFAULT_WINDOW_HEIGHT = 500;
const int DEFAULT_DISPLAY_X = 100;
const int DEFAULT_DISPLAY_Y = 100;

const int REDRAW_HFUNCTION_FLAG = 0x01;
const int RESIZE_HFUNCTION_FLAG = 0x02;
const int KEYBOARDDOWN_HFUNCTION_FLAG = 0x04;
const int KEYBOARDUP_HFUNCTION_FLAG = 0x08;
const int TIMER_HFUNCTION_FLAG = 0x10;
const int MOUSE_LFD_HFUNCTION_FLAG = 0x20;


enum MouseActionHandlersIndex {
      YURIGL_LEFT_DOWN, YURIGL_RIGHT_DOWN, YURIGL_MIDDLE_DOWN, YURIGL_LEFT_UP, YURIGL_RIGHT_UP, YURIGL_MIDDLE_UP
};

#endif