#ifndef VALUE_HXX
#define VALUE_HXX

const int DEFAULT_WINDOW_WIDTH = 500;
const int DEFAULT_WINDOW_HEIGHT = 500;
const int DEFAULT_DISPLAY_X = 100;
const int DEFAULT_DISPLAY_Y = 100;

enum MouseActionHandlersIndex {
      YURIGL_LEFT_DOWN, YURIGL_RIGHT_DOWN, YURIGL_MIDDLE_DOWN, YURIGL_LEFT_UP, YURIGL_RIGHT_UP, YURIGL_MIDDLE_UP
};

#endif